{lib, ...}:
with lib;
{
  imports = [
    ./ark.nix
    ./avidemux.nix
    ./bleachbit.nix
    ./blueman.nix
    ./calibre.nix
    ./chromium.nix
    ./cura.nix
    ./czkawka.nix
    ./diffuse.nix
    ./drawio.nix
    ./electrum.nix
    ./eog.nix
    ./feh.nix
    ./ferdium.nix
    ./file-roller.nix
    ./firefox.nix
    ./flameshot.nix
    ./floorp.nix
    ./geeqie.nix
    ./gnome-encfsmanager.nix
    ./gnome-software.nix
    ./gnome-systemmonitor.nix
    ./gparted.nix
    ./greenclip.nix
    ./kitty.nix
    ./libreoffice.nix
    ./masterpdfeditor.nix
    ./mate-calc.nix
    ./mqtt-explorer.nix
    ./nemo.nix
    ./nextcloud-client.nix
    ./obsidian.nix
    ./opensnitch-ui.nix
    ./peazip.nix
    ./pinta.nix
    ./pulsemixer.nix
    ./qview.nix
    ./remmina.nix
    ./rofi.nix
    ./seahorse.nix
    ./smartgit.nix
    ./smplayer.nix
    ./sqlitebrowser.nix
    ./strawberry.nix
    ./szyszka.nix
    ./thunar.nix
    ./thunderbird.nix
    ./veracrypt.nix
    ./virt-manager.nix
    ./vivaldi.nix
    ./vlc.nix
    ./vscode.nix
    ./wpsoffice.nix
    ./zenbrowser.nix
    ./zoom.nix
  ];
}
