{lib, ...}:

with lib;
{
  imports = [
    ./act.nix
    ./android-tools.nix
    ./bat.nix
    ./bash.nix
    ./btop.nix
    ./comma.nix
    ./diceware.nix
    ./direnv.nix
    ./docker-compose.nix
    ./duf.nix
    ./dust.nix
    ./encfs.nix
    ./file-compression.nix
    ./fzf.nix
    ./gh.nix
    ./git.nix
    ./gnupg.nix
    ./hadolint.nix
    ./hugo.nix
    ./htop.nix
    ./jq.nix
    ./lazygit.nix
    ./less.nix
    ./liquidprompt.nix
    ./lsd.nix
    ./mp3gain.nix
    ./mtr.nix
    ./nano.nix
    ./neofetch.nix
    ./neovim.nix
    ./ncdu.nix
    ./nixfmt.nix
    ./nmap.nix
    ./rclone.nix
    ./ripgrep.nix
    ./s3ql.nix
    ./secrets.nix
    ./shfmt.nix
    ./shellcheck.nix
    ./tea.nix
    ./timewarrior.nix
    ./tmux.nix
    ./wget.nix
    ./xdg-ninja.nix
    ./xmlstarlet.nix
    ./yq.nix
    ./yt-dlp.nix
    ./zathura.nix
    ./zoxide.nix
  ];
}
